language: java
git:
  depth: 3
matrix:
  include:
  - jdk: oraclejdk8
    env: DEPLOY=true
install: mvn install -DskipTests=true
script: mvn test -Dassembly.skipAssembly=true -B
after_success:
  - test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false 
    && mvn source:jar deploy --settings .travis-settings.xml -DskipTests=true -B
env:
  global:
  - secure: bBzbwpm/zS+ZthJglPPDaMgCeDjvYdUTPyYXDy02yuBO45C6Zt+6LP/9nGcLECRtfkKI0keoRRqHnOvkTsZD4DLrs95KnSQtyDi//bwXvpPELf844r0W/OsvbvfYd2sHtP5sosMA1YRnhrNL4gi0ziGSh+xPS152ZNrXoAmBM09TB969OEyfets0nE5tQF3MBrUTYahj+C+5QKmJjSN82qQsqVmRUKM0vsaQ0ubGrl+gdF+oC2uGmy4+mQW2lXI8bIt0aU6hIEq+CiFqEGeYssgL+wBd8+OiwVG1R5NJ7A18nVwOth9kR7l3XM44Qq41HOo9lteWJgBEOPoaUK4NJURDHRY1kBd3QrO/9ICwOvR8t85z1gZv9lShXhDDeqQnGFoQVjD8WhRAlqiLChrta4QVtE7MwhUShLW4CpDxx1Fb6rX9Ax0pZdAs9XF/AbZ3c3e2/c/mJJLV7QWPhTv7ksp34iwYBgvpbGvBR59+qvo8mUh5ylmjctrwZT5RIZdWbO07zqBvP1PmuLINiVjBHUMJvmtppLdxkXzzaabCOajt/CRhzrHvQqKki3RSitBj8tUFhxu6C9PQDbm18TdgSlYeOYPb9B1YRgt/0sKMrgADNGgihPII57J4tFMlrKne/DSPFBmx/ZTNuLeiIYskv0big/vsi2NT8li6SyIirXI= 
  - secure: T0OiSDXtqJj1X2mjaCWecburzMsd2/fWsjFJzANjW9rQSDmVNIvJb2wmN/R/QpwrjaTA4BdtIU8hfmebLUNUzqFlNf2qD0loTnnxfzp5PzEBb9KdDrvnACsaSA1P/jeAeogU6NFO4eBk+/OJV6Z9aSoszDedW4iUnoVbowil9Cxs+9kCRaBwAFIEDomGczwoqPSMG3mCn8XzXj7rjEZX95pLUy2wUZfK3fSz063WspDbj8w1mJz7kgmEGqUmkUCueyeKXgCWcL9EKeweDU3ybDYc6Yj1NSIoWzqqxbXYuAxj6XCCxy7tisL0q6esgcFBTR+X45XMqCUiuQD5nLVCshKunYpZ1OVgz9I5bcUIV3DWJExldaPvgG8PYdXrSVehRngnXGUsdAPLtZj0dT9MdpuZdNHLPCxusSpxIhr9+6jgapdwNBc2Js+ZlDcyi87+5n4JwYGGt26gU/W2gap8P14JYX2dCT7tPURJhTm3RiBH4kVTf6pYaZIrPVMCSwMUsJXKgVveTsTehGw76VyDpxU5Gh8p+NfAR/X2ca1hVrnvMawczF/FpaSnk9vFZLoJBHALAbBbCspK63pYBQXioN5DMJqeY8NnPaAGje0+Pu8V3Kw25f/puQz9/npF22aBokiD5kMemdkmSiTs6+Rf9BNwBi35GxMk9ga1wotojcY=
